package config

type CodeModel struct {
	Code int
	Name string
}

var EventCodes = map[string]any{
	"1":   CodeModel{Code: 1, Name: "Input 1 Active"},
	"2":   CodeModel{Code: 2, Name: "Input 2 Active"},
	"3":   CodeModel{Code: 3, Name: "Input 3 Active"},
	"9":   CodeModel{Code: 9, Name: "Input 1 Inactive"},
	"01": CodeModel{Code: 1, Name: "Input 1 Active"},
	"02": CodeModel{Code: 2, Name: "Input 2 Active"},
	"03": CodeModel{Code: 3, Name: "Input 3 Active"},
	"09": CodeModel{Code: 9, Name: "Input 1 Inactive"},
	"0A": CodeModel{Code: 10, Name: "Input 2 Inactive"},
	"0B": CodeModel{Code: 11, Name: "Input 3 Inactive"},
	"11": CodeModel{Code: 17, Name: "Low Battery"},
	"12": CodeModel{Code: 18, Name: "Low External Battery"},
	"13": CodeModel{Code: 19, Name: "Speeding"},
	"14": CodeModel{Code: 20, Name: "Enter Geo-fence"},
	"15": CodeModel{Code: 21, Name: "Exit Geo-fence"},
	"16": CodeModel{Code: 22, Name: "External Battery On"},
	"17": CodeModel{Code: 23, Name: "External Battery Cut"},
	"18": CodeModel{Code: 24, Name: "GPS Signal Lost"},
	"19": CodeModel{Code: 25, Name: "GPS Signal Recovery"},
	"1A": CodeModel{Code: 26, Name: "Enter Sleep"},
	"1B": CodeModel{Code: 27, Name: "Exit Sleep"},
	"1C": CodeModel{Code: 28, Name: "GPS Antenna Cut"},
	"1D": CodeModel{Code: 29, Name: "Device Reboot"},
	"1F": CodeModel{Code: 31, Name: "Heartbeat"},
	"20": CodeModel{Code: 32, Name: "Cornering"},
	"21": CodeModel{Code: 33, Name: "Track By Distance"},
	"22": CodeModel{Code: 34, Name: "Reply Current (Passive)"},
	"23": CodeModel{Code: 35, Name: "Track By Time Interval"},
	"24": CodeModel{Code: 36, Name: "Tow"},
	"25": CodeModel{Code: 37, Name: "iButton/RFID"},
	"27": CodeModel{Code: 39, Name: "Photo"},
	"28": CodeModel{Code: 40, Name: "Power Off"},
	"29": CodeModel{Code: 41, Name: "Stop Moving"},
	"2A": CodeModel{Code: 42, Name: "Start Moving"},
	"2C": CodeModel{Code: 44, Name: "GSM Jamming"},
	"32": CodeModel{Code: 50, Name: "Temperature High"},
	"33": CodeModel{Code: 51, Name: "Temperature Low"},
	"34": CodeModel{Code: 52, Name: "Full Fuel"},
	"35": CodeModel{Code: 53, Name: "Low Fuel"},
	"36": CodeModel{Code: 54, Name: "Fuel Theft"},
	"3F": CodeModel{Code: 63, Name: "No GSM Jamming"},
	"46": CodeModel{Code: 70, Name: "Reject Incoming Call"},
	"47": CodeModel{Code: 71, Name: "Get Location by Call"},
	"48": CodeModel{Code: 72, Name: "Auto Answer Incoming Call"},
	"49": CodeModel{Code: 73, Name: "Listen-in (Voice Monitoring)"},
	"4E": CodeModel{Code: 78, Name: "Impact"},
	"52": CodeModel{Code: 82, Name: "Fuel Filling"},
	"53": CodeModel{Code: 83, Name: "Ult-Sensor Drop"},
	"5A": CodeModel{Code: 90, Name: "Sharp Turn to Left"},
	"5B": CodeModel{Code: 91, Name: "Sharp Turn to Right"},
	"5E": CodeModel{Code: 94, Name: "Output 1 Active"},
	"5F": CodeModel{Code: 95, Name: "Output 2 Active"},
	"60": CodeModel{Code: 96, Name: "Output 1 Inactive"},
	"61": CodeModel{Code: 97, Name: "Output 2 Inactive"},
	"81": CodeModel{Code: 129, Name: "Harsh Braking"},
	"82": CodeModel{Code: 130, Name: "Harsh Acceleration"},
	"85": CodeModel{Code: 133, Name: "Idle Overtime"},
	"86": CodeModel{Code: 134, Name: "Idle Recovery"},
	"87": CodeModel{Code: 135, Name: "Fatigue Driving"},
	"88": CodeModel{Code: 136, Name: "Enough Rest after Fatigue Driving"},
}


var EventCodesAAA = map[string]any{
	"1":   CodeModel{Code: 1, Name: "Input 1 Active"},
	"2":   CodeModel{Code: 2, Name: "Input 2 Active"},
	"3":   CodeModel{Code: 3, Name: "Input 3 Active"},
	"9":   CodeModel{Code: 9, Name: "Input 1 Inactive"},
	"01": CodeModel{Code: 1, Name: "Input 1 Active"},
	"02": CodeModel{Code: 2, Name: "Input 2 Active"},
	"03": CodeModel{Code: 3, Name: "Input 3 Active"},
	"09": CodeModel{Code: 9, Name: "Input 1 Inactive"},
	"10": CodeModel{Code: 10, Name: "Input 2 Inactive"},
	"11": CodeModel{Code: 11, Name: "Input 3 Inactive"},
	"17": CodeModel{Code: 17, Name: "Low Battery"},
	"18": CodeModel{Code: 18, Name: "Low External Battery"},
	"19": CodeModel{Code: 19, Name: "Speeding"},
	"20": CodeModel{Code: 20, Name: "Enter Geo-fence"},
	"21": CodeModel{Code: 21, Name: "Exit Geo-fence"},
	"22": CodeModel{Code: 22, Name: "External Battery On"},
	"23": CodeModel{Code: 23, Name: "External Battery Cut"},
	"24": CodeModel{Code: 24, Name: "GPS Signal Lost"},
	"25": CodeModel{Code: 25, Name: "GPS Signal Recovery"},
	"26": CodeModel{Code: 26, Name: "Enter Sleep"},
	"27": CodeModel{Code: 27, Name: "Exit Sleep"},
	"28": CodeModel{Code: 28, Name: "GPS Antenna Cut"},
	"29": CodeModel{Code: 29, Name: "Device Reboot"},
	"31": CodeModel{Code: 31, Name: "Heartbeat"},
	"32": CodeModel{Code: 32, Name: "Cornering"},
	"33": CodeModel{Code: 33, Name: "Track By Distance"},
	"34": CodeModel{Code: 34, Name: "Reply Current (Passive)"},
	"35": CodeModel{Code: 35, Name: "Track By Time Interval"},
	"36": CodeModel{Code: 36, Name: "Tow"},
	"37": CodeModel{Code: 37, Name: "iButton/RFID"},
	"39": CodeModel{Code: 39, Name: "Photo"},
	"40": CodeModel{Code: 40, Name: "Power Off"},
	"41": CodeModel{Code: 41, Name: "Stop Moving"},
	"42": CodeModel{Code: 42, Name: "Start Moving"},
	"44": CodeModel{Code: 44, Name: "GSM Jamming"},
	"50": CodeModel{Code: 50, Name: "Temperature High"},
	"51": CodeModel{Code: 51, Name: "Temperature Low"},
	"52": CodeModel{Code: 52, Name: "Full Fuel"},
	"53": CodeModel{Code: 53, Name: "Low Fuel"},
	"54": CodeModel{Code: 54, Name: "Fuel Theft"},
	"63": CodeModel{Code: 63, Name: "No GSM Jamming"},
	"70": CodeModel{Code: 70, Name: "Reject Incoming Call"},
	"71": CodeModel{Code: 71, Name: "Get Location by Call"},
	"72": CodeModel{Code: 72, Name: "Auto Answer Incoming Call"},
	"73": CodeModel{Code: 73, Name: "Listen-in (Voice Monitoring)"},
	"78": CodeModel{Code: 78, Name: "Impact"},
	"82": CodeModel{Code: 82, Name: "Fuel Filling"},
	"83": CodeModel{Code: 83, Name: "Ult-Sensor Drop"},
	"90": CodeModel{Code: 90, Name: "Sharp Turn to Left"},
	"91": CodeModel{Code: 91, Name: "Sharp Turn to Right"},
	"94": CodeModel{Code: 94, Name: "Output 1 Active"},
	"95": CodeModel{Code: 95, Name: "Output 2 Active"},
	"96": CodeModel{Code: 96, Name: "Output 1 Inactive"},
	"97": CodeModel{Code: 97, Name: "Output 2 Inactive"},
	"129": CodeModel{Code: 129, Name: "Harsh Braking"},
	"130": CodeModel{Code: 130, Name: "Harsh Acceleration"},
	"133": CodeModel{Code: 133, Name: "Idle Overtime"},
	"134": CodeModel{Code: 134, Name: "Idle Recovery"},
	"135": CodeModel{Code: 135, Name: "Fatigue Driving"},
	"136": CodeModel{Code: 136, Name: "Enough Rest after Fatigue Driving"},
}
